# Site settings
title: Artem Gumennikov # site title
description: >- # site description
  Newborn indie hacker straight out of the game industry👾
lang: en-US # default lang
timezone: Europe/London # set your timezone
image: assets/img/personal-card.jpg # This image used for Open Graph more info https://ogp.me/
repo:  # site repo [optional]
mode: dark # default theme "dark" | "light"

# Profile settings
author:
  name: Artem Gumennikov # author name
  bio: >- # tell to the world
    From Russia with 👾
  username: flashag # general username
  github:  # github username
  twitter: f1ashag # twitter username
  facebook: artem.gumennikov # facebook username
  email: contact@flashag.net # email adress
  avatar: /assets/img/cv2.jpg # change with your own avatar

# URL settings
url: "https://flashag.net/" #
baseurl:
permalink: /:title/
google_analytics: # leave it blank if not wish
fb_appid:

# Collection setting
collections:
  posts:
    output: true
  blogs:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Homepage limit posts
number_of_posts: 15

# Homepage limit posts
number_of_articles: 15

# Build settings
# theme: klise
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
